#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Dotenv\Dotenv;

\date_default_timezone_set( 'Asia/Manila' );

$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

$application = new Application();

$application->add(new \App\Commands\LoginCommand());
$application->add(new \App\Commands\LogoutCommand());

$application->run();

